8
MSGNONE
26
Compile Tree - started ...
NROOT -1 0 
MSGNONE
34
 DE2_VGA:VGA compiled successfully
NROOT -1 0 
MSGWARN
22
Port disp_RGB is open.
NROOT -1 2 
BLKUNIT test_VGA $ DE2_VGA 
COMP $ C0 $ 
MSGWARN
19
Port hsync is open.
NROOT -1 2 
BLKUNIT test_VGA $ DE2_VGA 
COMP $ C0 $ 
MSGWARN
19
Port vsync is open.
NROOT -1 2 
BLKUNIT test_VGA $ DE2_VGA 
COMP $ C0 $ 
MSGWARN
40
Component has no connected output ports.
NROOT -1 2 
BLKUNIT test_VGA $ DE2_VGA 
COMP $ C0 $ 
MSGNONE
43
Unit DE2_VGA:test_VGA compiled successfully
NROOT -1 0 
MSGNONE
37
Compile Tree - completed successfully
NROOT -1 0 
