02.00 00 04 
0000003A 
00000000 
00000000 
00000000 
//--------------------------------------------------
//  
//      Verilog code generated by Visual HDL
//
//  Root of Design:
//  ---------------
//      Unit    Name  :  test_VGA
//      Library Name  :  DE2_VGA
//  
//      Creation Date :  Mon Oct 10 10:23:50 2022
//      Version       :  6.7.2-pc build 25 from Feb 19 2001
//  
//  Options Used:
//  -------------
//      Target
//         HDL        :  Verilog
//         Purpose    :  Simulation
//  
//      Style
//         Use tasks                      :  No
//         Code Destination               :  Combined file
//         Attach Directives              :  Yes
//         Structural                     :  No
//         Free text style                :  / / ...
//         Preserve spacing for free text :  Yes
//         Sort Ports by mode             :  No
//         Declaration alignment          :  No
//
//--------------------------------------------------
//--------------------------------------------------
//  
//  Library Name :  DE2_VGA
//  Unit    Name :  testsub_VGA
//  Unit    Type :  Text Unit
//  
//----------------------------------------------------
//////////////////////////////////////////
//////////////////////////////////////////
// Date        : Mon Oct 10 09:13:20 2022
//
// Author      : 
//
// Company     : 
//
// Description : 
//
//////////////////////////////////////////
//////////////////////////////////////////
`timescale 1ns/1ps

module  testsub_VGA (switch, clock);
   output [1:0] switch ;
   output clock ;

	reg [1:0] switch;
	reg 		 clock;

	initial
	begin
		switch <= 2'b00;
		clock  <= 1'b0;
	end

	always #10 clock <= ~clock;

endmodule
//--------------------------------------------------
//  
//  Library Name :  DE2_VGA
//  Unit    Name :  VGA
//  Unit    Type :  Text Unit
//  
//----------------------------------------------------
module VGA(
   clock,
   switch,
   disp_RGB,
   hsync,
   vsync
);
input  clock;     //?Y? 50MHz
input  [1:0]switch;
output [2:0]disp_RGB;    //VGARt4?
output  hsync;     //VGA	?
output  vsync;     //VGA]?

reg [9:0] hcount;     //VGA	W?
reg [9:0]   vcount;     //VGA]W?
reg [2:0]   data;
reg [2:0]  h_dat;
reg [2:0]   v_dat;
//reg [9:0]   timer;

reg   flag;
wire  hcount_ov;
wire  vcount_ov;
wire  dat_act;
wire  hsync;
wire   vsync;
reg  vga_clk; //VGA	]?RJ

parameter hsync_end   = 10'd95,
   hdat_begin  = 10'd143,
   hdat_end  = 10'd783,
   hpixel_end  = 10'd799,
   vsync_end  = 10'd1,
   vdat_begin  = 10'd34,
   vdat_end  = 10'd514,
   vline_end  = 10'd524;

initial
begin
  vga_clk <= 1'b0;
  hcount <= 10'd0;
  vcount <= 10'd0;
  data  <= 3'h0;
  v_dat <= 3'h0;
  h_dat <= 3'h0;
  flag  <= 1'b0;
end

always @(posedge clock)
begin
 vga_clk = ~vga_clk;
end

//************************VGAa,x******************************* 
//	?    

always @(posedge vga_clk)
begin
 if (hcount_ov)
  hcount <= 10'd0;
 else
  hcount <= hcount + 10'd1;
end
assign hcount_ov = (hcount == hpixel_end); //]?

always @(posedge vga_clk)
begin
 if (hcount_ov)
 begin
  if (vcount_ov)
   vcount <= 10'd0;
  else
   vcount <= vcount + 10'd1;
 end
end
assign  vcount_ov = (vcount == vline_end); //Rt? ?4

assign dat_act =    ((hcount >= hdat_begin) && (hcount < hdat_end))
     && ((vcount >= vdat_begin) && (vcount < vdat_end));
assign hsync = (hcount > hsync_end);
assign vsync = (vcount > vsync_end);
assign disp_RGB = (dat_act) ?  data : 3'h00;       

//************************?Rt?x******************************* 
//9?:??

/*always @(posedge vga_clk)
begin
 flag <= vcount_ov;
 if(vcount_ov && ~flag)
  timer <= timer + 1'b1;
end
*/

always @(posedge vga_clk)
begin
 case(switch[1:0])
  2'd0: data <= h_dat;      //ZH?
  2'd1: data <= v_dat;      //?H?
  2'd2: data <= (v_dat ^ h_dat); //SY??
  2'd3: data <= (v_dat ~^ h_dat); //SY??
 endcase
end

always @(posedge vga_clk)  //SY:H?

begin
 if(hcount < 223)
  v_dat <= 3'h7;      //?  
 else if(hcount < 303)
  v_dat <= 3'h6;   //
 else if(hcount < 383)
  v_dat <= 3'h5;   //?
 else if(hcount < 463)
  v_dat <= 3'h4;    //?
 else if(hcount < 543)
  v_dat <= 3'h3;   //?
 else if(hcount < 623)
  v_dat <= 3'h2;   //
 else if(hcount < 703)
  v_dat <= 3'h1;   //5
 else 
  v_dat <= 3'h0;   //?
end

always @(posedge vga_clk)  //SY??

begin
 if(vcount < 94)
  h_dat <= 3'h7;        //?
 else if(vcount < 154)
  h_dat <= 3'h6;   //
 else if(vcount < 214)
  h_dat <= 3'h5;   //?
 else if(vcount < 274)
  h_dat <= 3'h4;    //?
 else if(vcount < 334)
  h_dat <= 3'h3;   //?
 else if(vcount < 394)
  h_dat <= 3'h2;   //
 else if(vcount < 454)
  h_dat <= 3'h1;   //5
 else 
  h_dat <= 3'h0;   //?
end

endmodule





//--------------------------------------------------
//  
//  Library Name :  DE2_VGA
//  Unit    Name :  test_VGA
//  Unit    Type :  Block Diagram
//  
//----------------------------------------------------
 
 
module test_VGA;
 
  wire [1:0] switch;
 
  VGA  C0
    (
     .clock(clock),
     .switch(switch[1:0]),
     .disp_RGB(),
     .hsync(),
     .vsync());
 
  testsub_VGA  C1
    (
     .switch(switch[1:0]),
     .clock(clock));
 
 
endmodule


$RPR
NROOT -1 1 
VMODUNIT testsub_VGA $ DE2_VGA 
29 $B -1 NROOT -1 1 
VMODUNIT testsub_VGA $ DE2_VGA 
36 $N 1
37 $N 2
38 $N 3
39 $N 4
40 $N 5
41 $N 6
42 $N 7
43 $N 8
44 $N 9
45 $N 10
46 $N 11
47 $N 12
48 $N 13
49 $N 14
50 $N 15
51 $N 16
52 $N 17
53 $N 18
54 $N 19
55 $N 20
56 $N 21
57 $N 22
58 $N 23
59 $N 24
60 $N 25
61 $N 26
62 $N 27
63 $N 28
64 $N 29
65 $N 30
66 $B -1 NROOT -1 1 
VMODUNIT VGA $ DE2_VGA 
73 $N 1
74 $N 2
75 $N 3
76 $N 4
77 $N 5
78 $N 6
79 $N 7
80 $N 8
81 $N 9
82 $N 10
83 $N 11
84 $N 12
85 $N 13
86 $N 14
87 $N 15
88 $N 16
89 $N 17
90 $N 18
91 $N 19
92 $N 20
93 $N 21
94 $N 22
95 $N 23
96 $N 24
97 $N 25
98 $N 26
99 $N 27
100 $N 28
101 $N 29
102 $N 30
103 $N 31
104 $N 32
105 $N 33
106 $N 34
107 $N 35
108 $N 36
109 $N 37
110 $N 38
111 $N 39
112 $N 40
113 $N 41
114 $N 42
115 $N 43
116 $N 44
117 $N 45
118 $N 46
119 $N 47
120 $N 48
121 $N 49
122 $N 50
123 $N 51
124 $N 52
125 $N 53
126 $N 54
127 $N 55
128 $N 56
129 $N 57
130 $N 58
131 $N 59
132 $N 60
133 $N 61
134 $N 62
135 $N 63
136 $N 64
137 $N 65
138 $N 66
139 $N 67
140 $N 68
141 $N 69
142 $N 70
143 $N 71
144 $N 72
145 $N 73
146 $N 74
147 $N 75
148 $N 76
149 $N 77
150 $N 78
151 $N 79
152 $N 80
153 $N 81
154 $N 82
155 $N 83
156 $N 84
157 $N 85
158 $N 86
159 $N 87
160 $N 88
161 $N 89
162 $N 90
163 $N 91
164 $N 92
165 $N 93
166 $N 94
167 $N 95
168 $N 96
169 $N 97
170 $N 98
171 $N 99
172 $N 100
173 $N 101
174 $N 102
175 $N 103
176 $N 104
177 $N 105
178 $N 106
179 $N 107
180 $N 108
181 $N 109
182 $N 110
183 $N 111
184 $N 112
185 $N 113
186 $N 114
187 $N 115
188 $N 116
189 $N 117
190 $N 118
191 $N 119
192 $N 120
193 $N 121
194 $N 122
195 $N 123
196 $N 124
197 $N 125
198 $N 126
199 $N 127
200 $N 128
201 $N 129
202 $N 130
203 $N 131
204 $N 132
205 $N 133
206 $N 134
207 $N 135
208 $N 136
209 $N 137
210 $N 138
211 $N 139
212 $N 140
213 $N 141
214 $N 142
215 $N 143
216 $N 144
217 $N 145
218 $N 146
219 $N 147
220 $N 148
221 $N 149
222 $N 150
223 $N 151
224 $N 152
225 $B -1 NROOT -1 1 
BLKUNIT test_VGA $ DE2_VGA 
236 $N 1
238 $R 1 1 BLOK $ C0 $ 
239 $R 1 0 240 $N 1
241 $N 1
242 $N 1
243 $N 1
244 $N 1
246 $R 7 1 BLOK $ C1 $ 
247 $R 7 0 248 $N 7
249 $N 7
252 $N 7

-1
