12
MSGNONE
26
Compile Tree - started ...
NROOT -1 0 
MSGWARN
41
The signal VgaVsync is not read anywhere 
NROOT 17 2 
VMODUNIT testsub_VideoProc $ DE2_VGA 
NOBJ $ VgaVsync $ 
MSGWARN
36
The signal SDA is not read anywhere 
NROOT 16 2 
VMODUNIT testsub_VideoProc $ DE2_VGA 
NOBJ $ SDA $ 
MSGWARN
36
The signal SCL is not read anywhere 
NROOT 15 2 
VMODUNIT testsub_VideoProc $ DE2_VGA 
NOBJ $ SCL $ 
MSGWARN
41
The signal VgaDataR is not read anywhere 
NROOT 19 2 
VMODUNIT testsub_VideoProc $ DE2_VGA 
NOBJ $ VgaDataR $ 
MSGWARN
41
The signal VgaDataG is not read anywhere 
NROOT 20 2 
VMODUNIT testsub_VideoProc $ DE2_VGA 
NOBJ $ VgaDataG $ 
MSGWARN
37
The signal XCLK is not read anywhere 
NROOT 14 2 
VMODUNIT testsub_VideoProc $ DE2_VGA 
NOBJ $ XCLK $ 
MSGWARN
41
The signal VgaHsync is not read anywhere 
NROOT 18 2 
VMODUNIT testsub_VideoProc $ DE2_VGA 
NOBJ $ VgaHsync $ 
MSGWARN
41
The signal VgaDataB is not read anywhere 
NROOT 21 2 
VMODUNIT testsub_VideoProc $ DE2_VGA 
NOBJ $ VgaDataB $ 
MSGNONE
48
 DE2_VGA:testsub_VideoProc compiled successfully
NROOT -1 0 
MSGNONE
49
Unit DE2_VGA:test_VideoProc compiled successfully
NROOT -1 0 
MSGNONE
37
Compile Tree - completed successfully
NROOT -1 0 
