02.00 00 04 
0000003A 
00000000 
00000000 
00000000 
//--------------------------------------------------
//  
//      Verilog code generated by Visual HDL
//
//  Design Unit:
//  ------------
//      Unit    Name  :  test_VideoProc
//      Library Name  :  DE2_VGA
//  
//      Creation Date :  Fri Oct 14 17:19:33 2022
//      Version       :  6.7.2-pc build 25 from Feb 19 2001
//  
//  Options Used:
//  -------------
//      Target
//         HDL        :  Verilog
//         Purpose    :  Simulation
//  
//      Style
//         Use tasks                      :  No
//         Code Destination               :  1 File per Unit
//         Attach Directives              :  Yes
//         Structural                     :  No
//         Free text style                :  / / ...
//         Preserve spacing for free text :  Yes
//         Sort Ports by mode             :  No
//         Declaration alignment          :  No
//
//--------------------------------------------------
//--------------------------------------------------
//  
//  Library Name :  DE2_VGA
//  Unit    Name :  test_VideoProc
//  Unit    Type :  Block Diagram
//  
//----------------------------------------------------
 
 
module test_VideoProc;
 
  wire [7:0] CamData;
  wire [7:0] VgaDataB;
  wire [7:0] VgaDataG;
  wire [7:0] VgaDataR;
 
  VideoProc  C1_VideoProc
    (
     .CLK(CLK),
     .RST_N(RST_N),
     .XCLK(XCLK),
     .SCL(SCL),
     .SDA(SDA),
     .CamHsync(CamHsync),
     .CamVsync(CamVsync),
     .PCLK(PCLK),
     .CamData(CamData[7:0]),
     .VgaVsync(VgaVsync),
     .VgaHsync(VgaHsync),
     .SW0(SW0),
     .SW1(SW1),
     .VgaDataR(VgaDataR[7:0]),
     .VgaDataG(VgaDataG[7:0]),
     .VgaDataB(VgaDataB[7:0]));
 
  testsub_VideoProc  C0
    (
     .XCLK(XCLK),
     .SCL(SCL),
     .SDA(SDA),
     .VgaVsync(VgaVsync),
     .VgaHsync(VgaHsync),
     .VgaDataR(VgaDataR[7:0]),
     .VgaDataG(VgaDataG[7:0]),
     .VgaDataB(VgaDataB[7:0]),
     .CLK(CLK),
     .RST_N(RST_N),
     .CamHsync(),
     .CamVsync(),
     .PCLK(PCLK),
     .CamData(),
     .SW0(SW0),
     .SW1(SW1));
 
  testsub_cam  C3_PulseGen
    (
     .PCLK(PCLK),
     .RST_N(RST_N),
     .CamHsync(CamHsync),
     .CamVsync(CamVsync),
     .CamData(CamData[7:0]));
 
 
endmodule


$RPR
NROOT -1 1 
BLKUNIT test_VideoProc $ DE2_VGA 
29 $B -1 NROOT -1 1 
BLKUNIT test_VideoProc $ DE2_VGA 
40 $N 1
41 $N 2
42 $N 3
43 $N 4
45 $R 1 1 BLOK $ C1_VideoProc $ 
46 $R 1 0 47 $N 1
48 $N 1
49 $N 1
50 $N 1
51 $N 1
52 $N 1
53 $N 1
54 $N 1
55 $N 1
56 $N 1
57 $N 1
58 $N 1
59 $N 1
60 $N 1
61 $N 1
62 $N 1
64 $R 18 1 BLOK $ C0 $ 
65 $R 18 0 66 $N 18
67 $N 18
68 $N 18
69 $N 18
70 $N 18
71 $N 18
72 $N 18
73 $N 18
74 $N 18
75 $N 18
76 $N 18
77 $N 18
78 $N 18
79 $N 18
80 $N 18
81 $N 18
83 $R 35 1 BLOK $ C3_PulseGen $ 
84 $R 35 0 85 $N 35
86 $N 35
87 $N 35
88 $N 35
89 $N 35
92 $N 35

-1
