10
MSGNONE
26
Compile Tree - started ...
NROOT -1 0 
MSGERROR
59
INCOMPLETE DESIGN: Associated unit lcd_test00 doesn't exist
NROOT -1 2 
BLKUNIT top_de2 $ DE2_VGA 
BLOK $ lcd_inst0 $ 
MSGERROR
54
INCOMPLETE DESIGN: Associated unit nios2 doesn't exist
NROOT -1 2 
BLKUNIT PwmCtrl $ DE2_VGA 
BLOK $ u0 $ 
MSGNONE
44
 DE2_VGA:VideoProcCore compiled successfully
NROOT -1 0 
MSGWARN
47
The signal SDA is not driven and has no source 
NROOT 22 2 
VMODUNIT VideoProc $ DE2_VGA 
NOBJ $ SDA $ 
MSGWARN
47
The signal SCL is not driven and has no source 
NROOT 22 2 
VMODUNIT VideoProc $ DE2_VGA 
NOBJ $ SCL $ 
MSGNONE
40
 DE2_VGA:VideoProc compiled successfully
NROOT -1 0 
MSGWARN
65
Static checks: Associated  unit DE2_VGA:lcd_test00 does not exist
NROOT -1 0 
MSGNONE
38
 DE2_VGA:top_de2 compiled successfully
NROOT -1 0 
MSGNONE
21
Compile Tree - failed
NROOT -1 0 
